program PrjTestJsonDX121;

uses
  Vcl.Forms,
  FoMainDx in '..\src\FoMainDx.pas' {FormMain},
  Mc.Param in '..\src\Mc.Param.pas',
  TJ.Test in '..\src\TJ.Test.pas',
  TJ.TestSpeedRun in '..\src\TJ.TestSpeedRun.pas',
  TJ.TestValid in '..\src\TJ.TestValid.pas',
  TJ.TestFOpen in '..\src\TJ.TestFOpen.pas',
  TJ.Lib in '..\src\TJ.Lib.pas',
  TJ.LibMcJSON in '..\src\TJ.LibMcJSON.pas',
  TJ.LibLkJSON in '..\src\TJ.LibLkJSON.pas',
  TJ.LibSystemJSON in '..\src\TJ.LibSystemJSON.pas',
  TJ.LibJDO in '..\src\TJ.LibJDO.pas',
  TJ.LibSuperObject in '..\src\TJ.LibSuperObject.pas',
  TJ.LibXSuperObject in '..\src\TJ.LibXSuperObject.pas',
  TJ.LibJsonTools in '..\src\TJ.LibJsonTools.pas',
  TJ.LibJson4Delphi in '..\src\TJ.LibJson4Delphi.pas',
  TJ.LibGrijjyBson in '..\src\TJ.LibGrijjyBson.pas',
  TJ.LibNeslibJson in '..\src\TJ.LibNeslibJson.pas',
  TJ.LibDwsJSON in '..\src\TJ.LibDwsJSON.pas',
  TJ.LibChimeraJson in '..\src\TJ.LibChimeraJson.pas',
  TJ.LibDynamicDataObjects in '..\src\TJ.LibDynamicDataObjects.pas',
  TJ.LibEasyJson in '..\src\TJ.LibEasyJson.pas',
  TJ.LibJsonDoc in '..\src\TJ.LibJsonDoc.pas',
  McJSON in '..\src\pas\McJSON.pas',
  McUtils in '..\src\pas\McUtils.pas',
  uLkJSON in '..\src\pas\uLkJSON.pas',
  superobject in '..\src\pas\superobject\superobject.pas',
  XSuperObject in '..\src\pas\XSuperObject\XSuperObject.pas',
  JsonTools in '..\src\pas\JsonTools.pas',
  Jsons in '..\src\pas\Json4Delphi\Jsons.pas',
  Grijjy.Bson in '..\src\pas\Grijjy\Grijjy.Bson.pas',
  Neslib.Json in '..\src\pas\Neslib\Neslib.Json.pas',
  dwsJSON in '..\src\pas\DWScript\dwsJSON.pas',
  chimera.json in '..\src\pas\chimera\chimera.json.pas',
  DataObjects2 in '..\src\pas\DynamicDataObjects\DataObjects2.pas',
  DataObjects2JSON in '..\src\pas\DynamicDataObjects\DataObjects2JSON.pas',
  EasyJson in '..\src\pas\EasyJson.pas',
  jsonDoc in '..\src\pas\jsonDoc.pas',
  mormot.core.base in '..\src\pas\mORMot\mormot.core.base.pas',
  mormot.core.buffers in '..\src\pas\mORMot\mormot.core.buffers.pas',
  mormot.core.data in '..\src\pas\mORMot\mormot.core.data.pas',
  mormot.core.datetime in '..\src\pas\mORMot\mormot.core.datetime.pas',
  mormot.core.json in '..\src\pas\mORMot\mormot.core.json.pas',
  mormot.core.os in '..\src\pas\mORMot\mormot.core.os.pas',
  mormot.core.os.security in '..\src\pas\mORMot\mormot.core.os.security.pas',
  mormot.core.rtti in '..\src\pas\mORMot\mormot.core.rtti.pas',
  mormot.core.text in '..\src\pas\mORMot\mormot.core.text.pas',
  mormot.core.unicode in '..\src\pas\mORMot\mormot.core.unicode.pas',
  mormot.core.variants in '..\src\pas\mORMot\mormot.core.variants.pas',
  TJ.LibMormot in '..\src\TJ.LibMormot.pas',
  JsonDataObjects in '..\src\pas\JsonDataObjects\Source\JsonDataObjects.pas',
  TJ.LibVSoftYAML in '..\src\TJ.LibVSoftYAML.pas',
  VSoft.YAML.Classes in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Classes.pas',
  VSoft.YAML.IO in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.IO.pas',
  VSoft.YAML.Lexer in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Lexer.pas',
  VSoft.YAML.Parser in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Parser.pas',
  VSoft.YAML in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.pas',
  VSoft.YAML.Path in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Path.pas',
  VSoft.YAML.Polyfills in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Polyfills.pas',
  VSoft.YAML.StreamReader in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.StreamReader.pas',
  VSoft.YAML.StreamWriter in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.StreamWriter.pas',
  VSoft.YAML.TagInfo in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.TagInfo.pas',
  VSoft.YAML.Utils in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Utils.pas',
  VSoft.YAML.Writer.JSON in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Writer.JSON.pas',
  VSoft.YAML.Writer in '..\src\pas\vsoft.yaml\Source\VSoft.YAML.Writer.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
